# Generated by Django 5.2.1 on 2025-05-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_students'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_by_users', to='courses.course'),
        ),
    ]
